### ISSUE TITLE
Install script fails when PETSc configures HDF5

### ISSUE THREAD

**Issue by jayjaybillings** [xsdk-project/installxSDK#1]
I'm trying to install xSDK on a 64bit Fedora 23 box. xSDK fails when PETSc tries to build HDF5 with the following error:

> checking whether a simple MPI-IO program can be linked... noconfigure: WARNING: zlib.h: present but cannot be compiled
> configure: WARNING: zlib.h:     check for missing prerequisite headers?
> configure: WARNING: zlib.h: see the Autoconf documentation
> configure: WARNING: zlib.h:     section "Present But Cannot Be Compiled"
> configure: WARNING: zlib.h: proceeding with the compiler's result
> configure: WARNING:     ## -------------------------------- ##
> configure: WARNING:     ## Report this to help@hdfgroup.org ##
> configure: WARNING:     ## -------------------------------- ##
> configure: error: unable to link a simple MPI-IO application
> ---

I have zlib, zlib-devel and zlib-static installed for 64- and 32-bit architectures. I also can't get xSDK to point to the system install of HDF5, which is Fedora will install by default with OpenMPI. If I pull HDF5 1.8.17 from the HDF5 Group website and use the same configure options that PETSc uses, then it configures just fine.

**Comment by BarrySmith** [comment]
Please email the file configure.log it may be in petsc/configure.log and the ENTIRE HDF5 autconf output files from the failed hdf5 build to petsc-maint@mcs.anl.gov (sadly github doesn't allow uploading such large files).

**Comment by jayjaybillings** [comment]
Done. Please let me know if I missed a few files. If it is easier in the future, I can fork xSDK and upload the files in the fork.

**Comment by jayjaybillings** [comment]
@BarrySmith and @balay found the problem and submitted a bug to the Fedora team. 

https://bugzilla.redhat.com/show_bug.cgi?id=1375290

The bug was fixed and this problem is now fixed for me.
